language: generic

jobs:
  include:
    - name: JS lint and tests
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run build-test

    - name: PHP lint and tests
      install:
        - composer global require wp-coding-standards/wpcs
        - /vendor/bin/phpcs --config-set installed_paths /vendor/wp-coding-standards/wpcs
      script:
        - /vendor/bin/phpcs
