sudo: false

dist: trusty

language: generic

jobs:
  include:
    - name: JS lint and tests
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run test
