language: generic

before_install:
  - nvm install

jobs:
  include:
    - name: JS unit tests
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run build-test && ./node_modules/.bin/eslint src
