language: generic

before_install:
  - nvm install

jobs:
  include:
    - name: JS lint and tests
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run build-test

    - name: PHP lint and tests
      before_install:
        - composer global require wp-coding-standards/wpcs
        - phpcs --config-set installed_paths /composer/vendor/wp-coding-standards/wpcs
      script:
        - /composer/vendor/bin/phpcs --standard=phpcs.xml --extensions=php .
